// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceAgcDriver.sprx
// Analyzed provider SHA-256: bc2ca28f3632ce69e25ab44991ed1f49bc1624fe39c2fc81f2efc6e705876348
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class AgcDriverLleExports
{
    // Ghidra entry 0x4d90; body bytes 86.
    [SysAbiExport(
        Nid = "+T8Xo6LtFJI",
        ExportName = "sceAgcDriverAgrSubmitMultiDcbs",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x6ee0; body bytes 3.
    [SysAbiExport(
        Nid = "+TN0oRTBxJQ",
        ExportName = "sceAgcDriverIsTraceInProgress",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0xb00; body bytes 162.
    [SysAbiExport(
        Nid = "3AyTaWcF-H8",
        ExportName = "sceAgcDriverRegisterWorkloadStream",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x6d70; body bytes 11.
    [SysAbiExport(
        Nid = "5CdQTZIQPxM",
        ExportName = "sceAgcDriverGetEqEventType",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x7240; body bytes 6.
    [SysAbiExport(
        Nid = "5l3IfCFJxBs",
        ExportName = "sceAgcDriverFindResourcesPublic",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x2a30; body bytes 81.
    [SysAbiExport(
        Nid = "AhGvpITrf4M",
        ExportName = "sceAgcDriverAgrSubmitDcb",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x80d0; body bytes 3.
    [SysAbiExport(
        Nid = "Ddwk4gLT5j0",
        ExportName = "sceAgcDriverIsCaptureInProgress",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x80c0; body bytes 6.
    [SysAbiExport(
        Nid = "FOwvmNlFLjM",
        ExportName = "sceAgcDriverRequestCaptureStop",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x4df0; body bytes 67.
    [SysAbiExport(
        Nid = "HF3YllT3mXU",
        ExportName = "sceAgcDriverSubmitMultiAcbs",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x7310; body bytes 6.
    [SysAbiExport(
        Nid = "LepGrgk77sM",
        ExportName = "sceAgcDriverGetOwnerName",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x72b0; body bytes 6.
    [SysAbiExport(
        Nid = "M9yBzRKkjPc",
        ExportName = "sceAgcDriverGetResourceName",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x72d0; body bytes 6.
    [SysAbiExport(
        Nid = "NghWEUXp1qM",
        ExportName = "sceAgcDriverGetResourceBaseAddressAndSizeInBytes",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x80b0; body bytes 6.
    [SysAbiExport(
        Nid = "SAfhzJPcjuk",
        ExportName = "sceAgcDriverRequestCaptureStart",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x72f0; body bytes 6.
    [SysAbiExport(
        Nid = "VOMSpd9+vxU",
        ExportName = "sceAgcDriverSetResourceUserData",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x80a0; body bytes 6.
    [SysAbiExport(
        Nid = "Xq5WmbwPTnQ",
        ExportName = "sceAgcDriverTriggerCapture",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x71e0; body bytes 6.
    [SysAbiExport(
        Nid = "emP3ckeS2uo",
        ExportName = "sceAgcDriverRegisterGdsResource",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x72e0; body bytes 6.
    [SysAbiExport(
        Nid = "ls4jfY576lw",
        ExportName = "sceAgcDriverGetResourceUserData",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x7300; body bytes 6.
    [SysAbiExport(
        Nid = "mXn+K9E-wOA",
        ExportName = "sceAgcDriverGetResourceShaderGuid",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0xbb0; body bytes 120.
    [SysAbiExport(
        Nid = "n5ElQVYsU1A",
        ExportName = "sceAgcDriverUnregisterWorkloadStream",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x80e0; body bytes 3.
    [SysAbiExport(
        Nid = "qspAL8bgcBY",
        ExportName = "sceAgcDriverIsSubmitValidationEnabled",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x72c0; body bytes 6.
    [SysAbiExport(
        Nid = "rI9lNAXPMIw",
        ExportName = "sceAgcDriverGetResourceType",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    // Ghidra entry 0x6ef0; body bytes 6.
    [SysAbiExport(
        Nid = "rJUyMrDdxJg",
        ExportName = "sceAgcDriverGetShaderDebuggingStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceAgcDriver",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] AgcDriver LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
