// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceAgc.sprx
// Analyzed provider SHA-256: 110df81f759ae3dffcc9b5e3fa062c74058518631847641b8e08a54f6b8b6e2d
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class AgcLleExports
{
    // Ghidra entry 0x2b10; body bytes 736.
    [SysAbiExport(
        Nid = "03RZmELWWzw",
        ExportName = "sceAgcCbSetUcRegistersDirect",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd210; body bytes 6.
    [SysAbiExport(
        Nid = "0ZOG0jc9nRg",
        ExportName = "sceAgcAcbRewindGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x6b60; body bytes 165.
    [SysAbiExport(
        Nid = "0o3VDdtA6nM",
        ExportName = "sceAgcDcbSetIndexIndirectArgs",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x37b0; body bytes 282.
    [SysAbiExport(
        Nid = "1-gUn1PI4Sw",
        ExportName = "sceAgcDcbAtomicMem",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce30; body bytes 6.
    [SysAbiExport(
        Nid = "1DeUNpRIDDA",
        ExportName = "sceAgcDcbSetCxRegisterDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x4f00; body bytes 286.
    // Ghidra entry 0xce70; body bytes 6.
    [SysAbiExport(
        Nid = "1tB0xkLNjcw",
        ExportName = "sceAgcDcbAtomicGdsGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc6a0; body bytes 46.
    [SysAbiExport(
        Nid = "3ZWa3AoyWZQ",
        ExportName = "sceAgcAsyncCondExecPatchSetCommandAddress",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd050; body bytes 6.
    [SysAbiExport(
        Nid = "6DFuRKT4C9w",
        ExportName = "sceAgcDcbSetNumInstancesGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf30; body bytes 6.
    [SysAbiExport(
        Nid = "6ee9Hd3EWXQ",
        ExportName = "sceAgcDcbDrawIndexGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc210; body bytes 92.
    [SysAbiExport(
        Nid = "7Wa3aeJgeVU",
        ExportName = "7Wa3aeJgeVU#G#A",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x2230; body bytes 232.
    [SysAbiExport(
        Nid = "7toV+elXqNM",
        ExportName = "sceAgcCbCondWrite",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd000; body bytes 6.
    [SysAbiExport(
        Nid = "9S4noWrUI0s",
        ExportName = "sceAgcDcbSetBaseDispatchIndirectArgsGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7d60; body bytes 112.
    [SysAbiExport(
        Nid = "AAeX-U5-P3M",
        ExportName = "sceAgcGetDefaultCxStateFlat",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd150; body bytes 6.
    [SysAbiExport(
        Nid = "AFIh8SQkYlQ",
        ExportName = "sceAgcDcbSetIndexIndirectArgsGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcd60; body bytes 6.
    [SysAbiExport(
        Nid = "Abendgtz+3o",
        ExportName = "sceAgcCbDispatchGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcfd0; body bytes 22.
    [SysAbiExport(
        Nid = "C4l9fB17t8w",
        ExportName = "sceAgcDcbEventWriteGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd1c0; body bytes 6.
    [SysAbiExport(
        Nid = "CbQh3DKMSno",
        ExportName = "sceAgcAcbCopyDataGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1330; body bytes 161.
    [SysAbiExport(
        Nid = "DwICrVxerkY",
        ExportName = "sceAgcAcbRewind",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd280; body bytes 6.
    [SysAbiExport(
        Nid = "F8NLhWvFemI",
        ExportName = "sceAgcAcbQueueEndOfShaderActionGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1f30; body bytes 149.
    [SysAbiExport(
        Nid = "FcgdDM3MB+k",
        ExportName = "sceAgcAcbSetWorkloadStreamInactive",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7760; body bytes 141.
    [SysAbiExport(
        Nid = "FneFypEDRgY",
        ExportName = "sceAgcDcbSetWorkloadStreamInactive",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcd80; body bytes 6.
    [SysAbiExport(
        Nid = "FuVbkyKlf+s",
        ExportName = "sceAgcCbCondWriteGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7480; body bytes 399.
    [SysAbiExport(
        Nid = "G0jrLdvEqDw",
        ExportName = "sceAgcDcbMemSemaphore",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce00; body bytes 6.
    [SysAbiExport(
        Nid = "GBCh3zCihoU",
        ExportName = "sceAgcDcbSetCxRegistersIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1d30; body bytes 159.
    [SysAbiExport(
        Nid = "GPbUp9jXQa8",
        ExportName = "sceAgcAcbWaitUntilSafeForRendering",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc2d0; body bytes 54.
    [SysAbiExport(
        Nid = "GXBlM-ekzrI",
        ExportName = "sceAgcBranchPatchSetCompareAddress",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcea0; body bytes 23.
    [SysAbiExport(
        Nid = "H6vHS5cidSA",
        ExportName = "sceAgcDcbContextStateOpGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcdc0; body bytes 8.
    [SysAbiExport(
        Nid = "JOWmDrl+j20",
        ExportName = "sceAgcCbSetUcRegisterRangeDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc780; body bytes 7.
    [SysAbiExport(
        Nid = "K2mciNVxUCE",
        ExportName = "sceAgcSetNop",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd140; body bytes 6.
    [SysAbiExport(
        Nid = "KjPeVduz6jU",
        ExportName = "sceAgcDcbPrimeUtcl2GetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7610; body bytes 164.
    [SysAbiExport(
        Nid = "LFSPFmGc9Hg",
        ExportName = "sceAgcDcbSetWorkloadsActive",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x3350; body bytes 147.
    // Ghidra entry 0xc750; body bytes 34.
    [SysAbiExport(
        Nid = "Lkf86B98qPc",
        ExportName = "sceAgcGetPacketSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x2740; body bytes 218.
    [SysAbiExport(
        Nid = "MDLD5Ly94Xk",
        ExportName = "sceAgcCbSetUcRegisterRangeDirect",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd010; body bytes 6.
    [SysAbiExport(
        Nid = "MMlmJAL7N5w",
        ExportName = "sceAgcDcbSetBaseDrawIndirectArgsGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x10db0; body bytes 1202.
    [SysAbiExport(
        Nid = "NKIzURsgV7I",
        ExportName = "sceAgcGetGsOversubscription",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7a40; body bytes 199.
    [SysAbiExport(
        Nid = "OQTgEXyihvA",
        ExportName = "sceAgcSetAmmSemaphoreMemory",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc5d0; body bytes 76.
    [SysAbiExport(
        Nid = "ORWsxIbk4TE",
        ExportName = "sceAgcCondExecPatchSetEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd100; body bytes 6.
    [SysAbiExport(
        Nid = "P1CugZ99Uzc",
        ExportName = "sceAgcDcbEndOcclusionQueryGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd1e0; body bytes 6.
    [SysAbiExport(
        Nid = "PxKWV2fVAps",
        ExportName = "sceAgcAcbDispatchIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7060; body bytes 187.
    [SysAbiExport(
        Nid = "QhCbS4X9Rl8",
        ExportName = "sceAgcDcbSetMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce20; body bytes 6.
    [SysAbiExport(
        Nid = "QhPDD513V0w",
        ExportName = "sceAgcDcbSetShRegisterDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x5570; body bytes 345.
    [SysAbiExport(
        Nid = "Rlx+bykm0r0",
        ExportName = "sceAgcDcbDrawIndexMultiInstanced",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x9960; body bytes 5.
    [SysAbiExport(
        Nid = "T6xuVw0KUJo",
        ExportName = "sceAgcDebugRaiseException",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcde0; body bytes 7.
    [SysAbiExport(
        Nid = "TGEZzUWLbrc",
        ExportName = "sceAgcCbSetUcRegistersDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce10; body bytes 6.
    [SysAbiExport(
        Nid = "UQGTw4xRlcM",
        ExportName = "sceAgcDcbSetUcRegistersIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf20; body bytes 6.
    [SysAbiExport(
        Nid = "WrdP9Zxx3lQ",
        ExportName = "sceAgcDcbDrawIndexAutoGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd0; body bytes 280.
    [SysAbiExport(
        Nid = "XKKuA6VkSRc",
        ExportName = "sceAgcAcbAtomicMem",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd110; body bytes 6.
    [SysAbiExport(
        Nid = "XN+Iuu7XsM8",
        ExportName = "sceAgcDcbSetZPassPredicationEnableGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd1f0; body bytes 6.
    [SysAbiExport(
        Nid = "Y-5vneiBtzk",
        ExportName = "sceAgcAcbEventWriteGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x10d60; body bytes 68.
    [SysAbiExport(
        Nid = "Y3ymLfZ1384",
        ExportName = "sceAgcUpdatePrimState",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc620; body bytes 46.
    [SysAbiExport(
        Nid = "YWTKOju587o",
        ExportName = "sceAgcCondExecPatchSetCommandAddress",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd1b0; body bytes 6.
    // Ghidra entry 0xced0; body bytes 6.
    [SysAbiExport(
        Nid = "b5u0Jzm8TF8",
        ExportName = "sceAgcDcbCopyDataGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcdb0; body bytes 8.
    [SysAbiExport(
        Nid = "bxGoVxpdSPQ",
        ExportName = "sceAgcCbSetShRegisterRangeDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd020; body bytes 6.
    [SysAbiExport(
        Nid = "ca4KPvp0qLQ",
        ExportName = "sceAgcDcbSetIndexSizeGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf50; body bytes 6.
    [SysAbiExport(
        Nid = "cxPZ4Wgvdj8",
        ExportName = "sceAgcDcbDrawIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd190; body bytes 6.
    [SysAbiExport(
        Nid = "da1Sm8-QDoU",
        ExportName = "sceAgcAcbAtomicMemGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd80; body bytes 195.
    // Ghidra entry 0xd200; body bytes 6.
    [SysAbiExport(
        Nid = "eCjKaqeeQ5s",
        ExportName = "sceAgcAcbPrimeUtcl2GetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc700; body bytes 43.
    [SysAbiExport(
        Nid = "eWaWyFegzgQ",
        ExportName = "sceAgcAsyncRewindPatchSetRewindState",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1ae0; body bytes 174.
    [SysAbiExport(
        Nid = "ebixW91gpPw",
        ExportName = "sceAgcAcbSetFlip",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc550; body bytes 54.
    [SysAbiExport(
        Nid = "fRG-JOH5+sI",
        ExportName = "sceAgcSetUcRegIndirectPatchSetNumRegisters",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1610; body bytes 345.
    [SysAbiExport(
        Nid = "gQkqkLttcpw",
        ExportName = "gQkqkLttcpw#G#A",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x76c0; body bytes 157.
    [SysAbiExport(
        Nid = "hEK26Wdny6s",
        ExportName = "sceAgcDcbSetWorkloadComplete",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x7b10; body bytes 51.
    [SysAbiExport(
        Nid = "hFQ9pUxoLQ4",
        ExportName = "sceAgcGetSemaphoreLabel",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd180; body bytes 6.
    [SysAbiExport(
        Nid = "hcIxS8pmXF4",
        ExportName = "sceAgcAcbAtomicGdsGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd220; body bytes 85.
    [SysAbiExport(
        Nid = "idlaArvdXEs",
        ExportName = "sceAgcAcbWaitOnAddressGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd030; body bytes 6.
    [SysAbiExport(
        Nid = "j4emHHndCPY",
        ExportName = "sceAgcDcbSetIndexBufferGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x6a20; body bytes 213.
    [SysAbiExport(
        Nid = "jt3pl7EN17o",
        ExportName = "sceAgcDcbPrimeUtcl2",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc650; body bytes 76.
    [SysAbiExport(
        Nid = "k-JpyR2dYAM",
        ExportName = "sceAgcAsyncCondExecPatchSetEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x109e0; body bytes 537.
    [SysAbiExport(
        Nid = "k0E7vkgqAuE",
        ExportName = "k0E7vkgqAuE#G#A",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x5020; body bytes 490.
    [SysAbiExport(
        Nid = "kUlvghKs-mA",
        ExportName = "sceAgcDcbDrawIndirectMulti",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcfb0; body bytes 21.
    [SysAbiExport(
        Nid = "mR9j7+SfM34",
        ExportName = "sceAgcDcbDrawIndexMultiInstancedGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd0e0; body bytes 24.
    [SysAbiExport(
        Nid = "ms1xVoZ-Vwc",
        ExportName = "sceAgcDcbBeginOcclusionQueryGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc790; body bytes 87.
    [SysAbiExport(
        Nid = "n8vgpaQg6dA",
        ExportName = "sceAgcSetRangePredication",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc3f0; body bytes 54.
    [SysAbiExport(
        Nid = "nCUgItdN2ms",
        ExportName = "sceAgcSetShRegIndirectPatchSetNumRegisters",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcdf0; body bytes 6.
    [SysAbiExport(
        Nid = "nNlUtdDDvZ0",
        ExportName = "sceAgcDcbSetShRegistersIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1e80; body bytes 164.
    [SysAbiExport(
        Nid = "opR1JeJZCBU",
        ExportName = "sceAgcAcbSetWorkloadComplete",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce90; body bytes 6.
    [SysAbiExport(
        Nid = "ou16V5hh5sg",
        ExportName = "sceAgcDcbCondExecGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xce80; body bytes 6.
    [SysAbiExport(
        Nid = "oz6zQq1JwCE",
        ExportName = "sceAgcDcbAtomicMemGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd1a0; body bytes 6.
    [SysAbiExport(
        Nid = "ozKzBP4aki4",
        ExportName = "sceAgcAcbCondExecGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcef0; body bytes 8.
    [SysAbiExport(
        Nid = "p9tI+yTvx68",
        ExportName = "sceAgcDcbWriteDataGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf60; body bytes 21.
    [SysAbiExport(
        Nid = "pYoKs3lPy88",
        ExportName = "sceAgcDcbDrawIndirectMultiGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1b90; body bytes 402.
    [SysAbiExport(
        Nid = "q4VuU-QsLOE",
        ExportName = "sceAgcAcbMemSemaphore",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf40; body bytes 6.
    [SysAbiExport(
        Nid = "qMlfB1ZhMDc",
        ExportName = "sceAgcDcbDrawIndexOffsetGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x460; body bytes 173.
    [SysAbiExport(
        Nid = "qyM2bxYFPAk",
        ExportName = "sceAgcAcbCondExec",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x510; body bytes 268.
    [SysAbiExport(
        Nid = "qzMN2XKGA4k",
        ExportName = "sceAgcAcbCopyData",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf80; body bytes 21.
    // Ghidra entry 0xc270; body bytes 90.
    [SysAbiExport(
        Nid = "rP5xLdOf26k",
        ExportName = "rP5xLdOf26k#G#A",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1dd0; body bytes 172.
    [SysAbiExport(
        Nid = "rVOmPz2RBlg",
        ExportName = "sceAgcAcbSetWorkloadsActive",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc840; body bytes 73.
    [SysAbiExport(
        Nid = "s+VGAMDQ0AQ",
        ExportName = "sceAgcGetDataPacketPayloadRange",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x13e0; body bytes 208.
    [SysAbiExport(
        Nid = "szG7hz2yEhA",
        ExportName = "sceAgcAcbPrimeUtcl2",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcd70; body bytes 6.
    // Ghidra entry 0xd130; body bytes 6.
    [SysAbiExport(
        Nid = "vLrBL8DQiz8",
        ExportName = "sceAgcDcbSetPredicationDisableGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1fd0; body bytes 413.
    // Ghidra entry 0xcf10; body bytes 6.
    [SysAbiExport(
        Nid = "w8HVkEeXPv8",
        ExportName = "sceAgcDcbDispatchIndirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xc4a0; body bytes 54.
    [SysAbiExport(
        Nid = "whb1RL7K4Ss",
        ExportName = "sceAgcSetCxRegIndirectPatchSetNumRegisters",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x1820; body bytes 188.
    [SysAbiExport(
        Nid = "xAeBOa0A3kk",
        ExportName = "sceAgcAcbSetMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcdd0; body bytes 7.
    [SysAbiExport(
        Nid = "yUBESvCCJ4I",
        ExportName = "sceAgcCbSetShRegistersDirectGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xd120; body bytes 6.
    [SysAbiExport(
        Nid = "yheJGN-ay+A",
        ExportName = "sceAgcDcbSetBoolPredicationEnableGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0x5210; body bytes 504.
    // Ghidra entry 0x6e50; body bytes 352.
    [SysAbiExport(
        Nid = "zARR5aCmkoY",
        ExportName = "zARR5aCmkoY#G#A",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    // Ghidra entry 0xcf00; body bytes 6.
    [SysAbiExport(
        Nid = "zg6u-N6Otxs",
        ExportName = "sceAgcDcbQueueEndOfShaderActionGetSize",
        Target = Generation.Gen5,
        LibraryName = "libSceAgc",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Agc LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
