// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceAmpr.sprx
// Analyzed provider SHA-256: 129a972cdb762d1b362ad136cdb802f5cac7d3a5f48ecb8b7e5d695c70af4047
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class AmprLleExports
{
    // Ghidra entry 0x3c70; body bytes 58.
    [SysAbiExport(
        Nid = "0BMj1hgG+kE",
        ExportName = "sceAmprMeasureCommandSizeWaitOnAddress_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4350; body bytes 53.
    [SysAbiExport(
        Nid = "0RdLmAh7WVo",
        ExportName = "sceAmprMeasureCommandSizePushMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3ef0; body bytes 47.
    [SysAbiExport(
        Nid = "2Hw8gjMdwSY",
        ExportName = "sceAmprMeasureCommandSizeWriteAddressFromCounterPair_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x42e0; body bytes 97.
    [SysAbiExport(
        Nid = "3OfeY4pzDV0",
        ExportName = "sceAmprMeasureCommandSizePushMarkerWithColor",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2f70; body bytes 773.
    [SysAbiExport(
        Nid = "4UkZbYKVF7c",
        ExportName = "sceAmprCommandBufferConstructMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x32e0; body bytes 68.
    [SysAbiExport(
        Nid = "4quckD2y7Pg",
        ExportName = "sceAmprCommandBufferSetMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4110; body bytes 21.
    [SysAbiExport(
        Nid = "7nXGDGMXSqo",
        ExportName = "sceAmprMeasureCommandSizeReadFileScatter",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x37e0; body bytes 300.
    [SysAbiExport(
        Nid = "BVmR1H8l+XI",
        ExportName = "sceAmprAprCommandBufferReadFileGatherScatter",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3cf0; body bytes 170.
    [SysAbiExport(
        Nid = "ClnsFLLLcss",
        ExportName = "sceAmprMeasureCommandSizeWaitOnCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x1eb0; body bytes 328.
    [SysAbiExport(
        Nid = "DLfoNxTFNVk",
        ExportName = "sceAmprCommandBufferWaitOnAddress_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4130; body bytes 42.
    [SysAbiExport(
        Nid = "DXmgc5op8Yw",
        ExportName = "sceAmprMeasureCommandSizeReadFileGatherScatter",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3990; body bytes 274.
    [SysAbiExport(
        Nid = "Eul7AGEpjLo",
        ExportName = "sceAmprAprCommandBufferMapBegin",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2c80; body bytes 309.
    [SysAbiExport(
        Nid = "GmOguNIsuKk",
        ExportName = "sceAmprCommandBufferConstructNop",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3f50; body bytes 133.
    [SysAbiExport(
        Nid = "I-Qm+MEso5c",
        ExportName = "sceAmprMeasureCommandSizeWriteCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3e90; body bytes 47.
    [SysAbiExport(
        Nid = "JYd9g9L+TmE",
        ExportName = "sceAmprMeasureCommandSizeWriteAddressFromCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3710; body bytes 198.
    [SysAbiExport(
        Nid = "Jg-AgkdJHkk",
        ExportName = "sceAmprAprCommandBufferReadFileScatter",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4050; body bytes 28.
    [SysAbiExport(
        Nid = "NNIZ-FMyz3M",
        ExportName = "sceAmprMeasureCommandSizeNop",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x1e80; body bytes 5.
    [SysAbiExport(
        Nid = "RPCAhx-aabE",
        ExportName = "sceAmprCommandBufferGetBufferBaseAddress",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x1e60; body bytes 3.
    [SysAbiExport(
        Nid = "VEDMaQmJZng",
        ExportName = "sceAmprCommandBufferGetType",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x42a0; body bytes 53.
    [SysAbiExport(
        Nid = "VGkEj4d6-Kg",
        ExportName = "sceAmprMeasureCommandSizeSetMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3be0; body bytes 129.
    [SysAbiExport(
        Nid = "X169CE6G3Y4",
        ExportName = "sceAmprAprCommandBufferMapEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4070; body bytes 28.
    [SysAbiExport(
        Nid = "Xp85BP3+BBI",
        ExportName = "sceAmprMeasureCommandSizeNopWithData",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3910; body bytes 122.
    [SysAbiExport(
        Nid = "YPxkUDhgoNI",
        ExportName = "sceAmprAprCommandBufferResetGatherScatterState",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3ab0; body bytes 301.
    [SysAbiExport(
        Nid = "bFEs0Gs6D2A",
        ExportName = "sceAmprAprCommandBufferMapDirectBegin",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2b50; body bytes 34.
    [SysAbiExport(
        Nid = "bt3LHR9xjK4",
        ExportName = "sceAmprCommandBufferWriteAddressFromTimeCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2150; body bytes 297.
    [SysAbiExport(
        Nid = "cQb8Zr8Q0Y0",
        ExportName = "sceAmprCommandBufferWaitOnCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x33b0; body bytes 68.
    [SysAbiExport(
        Nid = "dXPaz65HNmk",
        ExportName = "sceAmprCommandBufferPushMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2c10; body bytes 49.
    [SysAbiExport(
        Nid = "enZm-6GjWqw",
        ExportName = "sceAmprCommandBufferWriteAddressFromCounterPair_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3330; body bytes 115.
    [SysAbiExport(
        Nid = "f12ObAMEi9A",
        ExportName = "sceAmprCommandBufferPushMarkerWithColor",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3e50; body bytes 28.
    [SysAbiExport(
        Nid = "gAtc79UTt5E",
        ExportName = "sceAmprMeasureCommandSizeWriteAddressFromTimeCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4220; body bytes 6.
    [SysAbiExport(
        Nid = "iwTNhyaemnw",
        ExportName = "sceAmprMeasureCommandSizeMapEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2630; body bytes 234.
    [SysAbiExport(
        Nid = "jK+yuYCI7MA",
        ExportName = "sceAmprCommandBufferWriteCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4170; body bytes 80.
    [SysAbiExport(
        Nid = "kdFImtTD0hc",
        ExportName = "sceAmprMeasureCommandSizeMapBegin",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3610; body bytes 251.
    [SysAbiExport(
        Nid = "mZSbNJVJpV8",
        ExportName = "sceAmprAprCommandBufferReadFileGather",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3400; body bytes 132.
    [SysAbiExport(
        Nid = "mv0O8Zg0woU",
        ExportName = "sceAmprCommandBufferPopMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2e70; body bytes 252.
    [SysAbiExport(
        Nid = "pFQ9UHpO52s",
        ExportName = "sceAmprCommandBufferNopWithData",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4390; body bytes 6.
    [SysAbiExport(
        Nid = "pbnNnahE8vk",
        ExportName = "sceAmprMeasureCommandSizePopMarker",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x40e0; body bytes 45.
    [SysAbiExport(
        Nid = "qesF88X4DRg",
        ExportName = "sceAmprMeasureCommandSizeReadFileGather",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x41c0; body bytes 88.
    [SysAbiExport(
        Nid = "qvbdJc7bG+s",
        ExportName = "sceAmprMeasureCommandSizeMapDirectBegin",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4160; body bytes 6.
    [SysAbiExport(
        Nid = "rddQYXM0CjM",
        ExportName = "sceAmprMeasureCommandSizeResetGatherScatterState",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x3280; body bytes 85.
    [SysAbiExport(
        Nid = "sWbST0oQKsc",
        ExportName = "sceAmprCommandBufferSetMarkerWithColor",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2bb0; body bytes 48.
    [SysAbiExport(
        Nid = "t4ExS+SwLjs",
        ExportName = "sceAmprCommandBufferWriteAddressFromCounter_04_00",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x2dc0; body bytes 166.
    [SysAbiExport(
        Nid = "tNn5WBkta60",
        ExportName = "sceAmprCommandBufferNop",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    // Ghidra entry 0x4230; body bytes 97.
    [SysAbiExport(
        Nid = "tmfr97+ED5I",
        ExportName = "sceAmprMeasureCommandSizeSetMarkerWithColor",
        Target = Generation.Gen5,
        LibraryName = "libSceAmpr",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Ampr LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
