// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceContentExport.sprx
// Analyzed provider SHA-256: a0a5564e5fa5a949af5f73db9f0b81550c413b1474a06e29d8f713538b35d5e7
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ContentExportLleExports
{
    // Ghidra entry 000028c0; body addresses 401.
    [SysAbiExport(
        Nid = "+KDWny9Y-6k",
        ExportName = "sceContentExportTerm",
        Target = Generation.Gen5,
        LibraryName = "libSceContentExport",
        PreferLle = true)]
    // Ghidra entry 00002a60; body addresses 389.
    [SysAbiExport(
        Nid = "FCygF4Ec4so",
        ExportName = "sceContentExportStart",
        Target = Generation.Gen5,
        LibraryName = "libSceContentExport",
        PreferLle = true)]
    // Ghidra entry 00002ee0; body addresses 651.
    [SysAbiExport(
        Nid = "OWCJUmrWH1g",
        ExportName = "sceContentExportFromFile",
        Target = Generation.Gen5,
        LibraryName = "libSceContentExport",
        PreferLle = true)]
    // Ghidra entry 000033d0; body addresses 155.
    [SysAbiExport(
        Nid = "mbakKLPSO4o",
        ExportName = "sceContentExportFromFileWithThumbnail",
        Target = Generation.Gen5,
        LibraryName = "libSceContentExport",
        PreferLle = true)]
    // Ghidra entry 00002ca0; body addresses 563.
    [SysAbiExport(
        Nid = "tb3cZTCl8Ps",
        ExportName = "sceContentExportFinish",
        Target = Generation.Gen5,
        LibraryName = "libSceContentExport",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] ContentExport LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
