// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceContentDelete.sprx
// Analyzed provider SHA-256: 0ad321f0f820ce2a08227a2bcf2050bc8abe349c63a7d71d1b7d1ef02d92e77c
// Each registration prefers the loaded guest export. Most HLE fallbacks remain
// fail-closed; sceContentDeleteInitialize has a Ghidra-backed lifecycle fallback.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ContentDeleteLleExports
{
    private const int ContentDeleteErrorInvalidArgument = unchecked((int)0x809D5001);
    private const int ContentDeleteErrorAlreadyInitialized = unchecked((int)0x809D5003);

    private static readonly object StateGate = new();
    private static int _initialized;

    // Ghidra entry 00000650; body addresses 66.
    [SysAbiExport(
        Nid = "5XLSih32qHA",
        ExportName = "sceContentDeleteTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    // Ghidra entry 000007a0; body addresses 458.
    [SysAbiExport(
        Nid = "qC3QW+AltHs",
        ExportName = "sceContentDeleteByPath",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] ContentDelete LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }

    // Ghidra entry 000005d0; body addresses 120. The provider validates the
    // parameter and its +0x08 pool-size field before checking lifecycle state.
    [SysAbiExport(
        Nid = "zoxb0wEChEM",
        ExportName = "sceContentDeleteInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceContentDelete",
        PreferLle = true)]
    public static int InitializeWithoutGuestProvider(CpuContext ctx)
    {
        lock (StateGate)
        {
            var parameterAddress = ctx[CpuRegister.Rdi];
            if (parameterAddress == 0 || parameterAddress > ulong.MaxValue - sizeof(ulong))
            {
                return ctx.SetReturn(ContentDeleteErrorInvalidArgument);
            }

            if (!ctx.TryReadUInt64(parameterAddress + sizeof(ulong), out var poolSize))
            {
                return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);
            }

            if (poolSize != 0x4000)
            {
                return ctx.SetReturn(ContentDeleteErrorInvalidArgument);
            }

            if (_initialized != 0)
            {
                return ctx.SetReturn(ContentDeleteErrorAlreadyInitialized);
            }

            _initialized = 1;
            return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
        }
    }

    internal static void ResetForTests()
    {
        lock (StateGate)
        {
            _initialized = 0;
        }
    }
}
