// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceImeDialog.sprx
// Analyzed provider SHA-256: 78324a0cbeb0ed78df0abb200c840ad4d4b5307e2f245ea2ebdaa09f28dea4cb
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ImeDialogLleExports
{
    // Ghidra entry 00000500; body addresses 1426.
    [SysAbiExport(
        Nid = "CRD+jSErEJQ",
        ExportName = "sceImeDialogGetPanelSizeExtended",
        Target = Generation.Gen5,
        LibraryName = "libSceImeDialog",
        PreferLle = true)]
    // Ghidra entry 00001610; body addresses 738.
    // Ghidra entry 00000bd0; body addresses 2609.
    // Ghidra entry 000019a0; body addresses 273.
    // Ghidra entry 00001900; body addresses 331.
    // Ghidra entry 00001920; body addresses 618.
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] ImeDialog LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
