// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNetCtl.sprx
// Analyzed provider SHA-256: 8ef1a46c912528979daa7dad7bee48df808793f3aede0545b0453d19ecf7c38b
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NetCtlLleExports
{
    // Ghidra entry 000032d0; body addresses 42.
    [SysAbiExport(
        Nid = "0cBgduPRR+M",
        ExportName = "sceNetCtlGetResult",
        Target = Generation.Gen5,
        LibraryName = "libSceNetCtl",
        PreferLle = true)]
    // Ghidra entry 000025c0; body addresses 115.
    [SysAbiExport(
        Nid = "Rqm2OnZMCz0",
        ExportName = "sceNetCtlUnregisterCallback",
        Target = Generation.Gen5,
        LibraryName = "libSceNetCtl",
        PreferLle = true)]
    // Ghidra entry 00002110; body addresses 1.
    [SysAbiExport(
        Nid = "Z4wwCFiBELQ",
        ExportName = "sceNetCtlTerm",
        Target = Generation.Gen5,
        LibraryName = "libSceNetCtl",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NetCtl LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
