// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNet.sprx
// Analyzed provider SHA-256: c04e1735a3f80a502c120610a43d0d37741f7ef90040d6b9d3346cc43988c64d
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NetLleExports
{
    // Ghidra entry 00004320; body addresses 11.
    [SysAbiExport(
        Nid = "9wO9XrMsNhc",
        ExportName = "sceNetRecv",
        Target = Generation.Gen5,
        LibraryName = "libSceNet",
        PreferLle = true)]
    // Ghidra entry 00003610; body addresses 230.
    [SysAbiExport(
        Nid = "Nd91WaWmG2w",
        ExportName = "sceNetResolverStartNtoa",
        Target = Generation.Gen5,
        LibraryName = "libSceNet",
        PreferLle = true)]
    // Ghidra entry 000042f0; body addresses 11.
    [SysAbiExport(
        Nid = "beRjXBn-z+o",
        ExportName = "sceNetSend",
        Target = Generation.Gen5,
        LibraryName = "libSceNet",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Net LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
