// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpAuth.sprx
// Analyzed provider SHA-256: 8492348ec1cf7be009b7b5f80a52b71ebb04e73998e55e26b2e03aac8e01edda
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpAuthLleExports
{
    // Ghidra entry 00002550; body addresses 42.
    [SysAbiExport(
        Nid = "H8wG9Bk-nPc",
        ExportName = "sceNpAuthDeleteRequest",
        Target = Generation.Gen5,
        LibraryName = "libSceNpAuth",
        PreferLle = true)]
    // Ghidra entry 00002830; body addresses 64.
    [SysAbiExport(
        Nid = "KI4dHLlTNl0",
        ExportName = "sceNpAuthGetAuthorizationCodeV3",
        Target = Generation.Gen5,
        LibraryName = "libSceNpAuth",
        PreferLle = true)]
    // Ghidra entry 00002500; body addresses 77.
    [SysAbiExport(
        Nid = "N+mr7GjTvr8",
        ExportName = "sceNpAuthCreateAsyncRequest",
        Target = Generation.Gen5,
        LibraryName = "libSceNpAuth",
        PreferLle = true)]
    // Ghidra entry 00002580; body addresses 42.
    [SysAbiExport(
        Nid = "cE7wIsqXdZ8",
        ExportName = "sceNpAuthAbortRequest",
        Target = Generation.Gen5,
        LibraryName = "libSceNpAuth",
        PreferLle = true)]
    // Ghidra entry 00002790; body addresses 148.
    [SysAbiExport(
        Nid = "gjSyfzSsDcE",
        ExportName = "sceNpAuthPollAsync",
        Target = Generation.Gen5,
        LibraryName = "libSceNpAuth",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpAuth LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
