// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceNpCommerce.sprx
// Analyzed provider SHA-256: 7ad70ea553cdff96d91394c79e5484dc49f20d17b681862fb3dfdf098006b7b3
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpCommerceLleExports
{
    // Ghidra entry 00000bf0; body addresses 12.
    [SysAbiExport(
        Nid = "0aR2aWmQal4",
        ExportName = "sceNpCommerceDialogInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00000b40; body addresses 54.
    [SysAbiExport(
        Nid = "DHmwsa6S8Tc",
        ExportName = "sceNpCommerceShowPsStoreIcon",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00000cd0; body addresses 124.
    [SysAbiExport(
        Nid = "DfSCDRA3EjY",
        ExportName = "sceNpCommerceDialogOpen",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00000dd0; body addresses 120.
    [SysAbiExport(
        Nid = "LR5cwFMMCVE",
        ExportName = "sceNpCommerceDialogUpdateStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00000b80; body addresses 26.
    [SysAbiExport(
        Nid = "dsqCVsNM0Zg",
        ExportName = "sceNpCommerceHidePsStoreIcon",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00001070; body addresses 77.
    [SysAbiExport(
        Nid = "m-I92Ab50W8",
        ExportName = "sceNpCommerceDialogTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    // Ghidra entry 00000eb0; body addresses 277.
    [SysAbiExport(
        Nid = "r42bWcQbtZY",
        ExportName = "sceNpCommerceDialogGetResult",
        Target = Generation.Gen5,
        LibraryName = "libSceNpCommerce",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpCommerce LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
