// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpEntitlementAccess.sprx
// Analyzed provider SHA-256: 13fbe892dbdea424b46d2c65fdf8b82441516f4dc7089c55bb4e00fc3df68820
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpEntitlementAccessLleExports
{
    // Ghidra entry 00000f90; body addresses 21.
    [SysAbiExport(
        Nid = "69u+XqsoNd0",
        ExportName = "sceNpEntitlementAccessPollConsumeEntitlement",
        Target = Generation.Gen5,
        LibraryName = "libSceNpEntitlementAccess",
        PreferLle = true)]
    // Ghidra entry 00001140; body addresses 15.
    [SysAbiExport(
        Nid = "HFcQl9TMcFQ",
        ExportName = "sceNpEntitlementAccessAbortRequest",
        Target = Generation.Gen5,
        LibraryName = "libSceNpEntitlementAccess",
        PreferLle = true)]
    // Ghidra entry 00000ef0; body addresses 15.
    [SysAbiExport(
        Nid = "IQtb-TaIjSM",
        ExportName = "sceNpEntitlementAccessGenerateTransactionId",
        Target = Generation.Gen5,
        LibraryName = "libSceNpEntitlementAccess",
        PreferLle = true)]
    // Ghidra entry 00001130; body addresses 15.
    [SysAbiExport(
        Nid = "Z0eQj8m7XA8",
        ExportName = "sceNpEntitlementAccessDeleteRequest",
        Target = Generation.Gen5,
        LibraryName = "libSceNpEntitlementAccess",
        PreferLle = true)]
    // Ghidra entry 00000f30; body addresses 46.
    [SysAbiExport(
        Nid = "eOxGbG3sPb0",
        ExportName = "sceNpEntitlementAccessRequestConsumeUnifiedEntitlement",
        Target = Generation.Gen5,
        LibraryName = "libSceNpEntitlementAccess",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpEntitlementAccess LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
