// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpGameIntent.sprx
// Analyzed provider SHA-256: 7b8533f64300c45e45db6fb120c2609a3fcda7b05b0052aecc9a080c77b771ad
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpGameIntentLleExports
{
    // Ghidra entry 00000900; body addresses 90.
    [SysAbiExport(
        Nid = "jEIXUAr9XE8",
        ExportName = "sceNpGameIntentReceiveIntent",
        Target = Generation.Gen5,
        LibraryName = "libSceNpGameIntent",
        PreferLle = true)]
    // Ghidra entry 00000960; body addresses 228.
    [SysAbiExport(
        Nid = "rPl0INNc-M8",
        ExportName = "sceNpGameIntentGetPropertyValueString",
        Target = Generation.Gen5,
        LibraryName = "libSceNpGameIntent",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpGameIntent LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
