// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpManager.sprx
// Analyzed provider SHA-256: 2c192ec03cf2b3a8acc24c2aefd98ef8232c2bdbdf2f678deb980397ed48cb72
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpManagerLleExports
{
    // Ghidra entry 00017c40; body addresses 341.
    [SysAbiExport(
        Nid = "+4DegjBqV1g",
        ExportName = "sceNpGetAccountAge",
        Target = Generation.Gen5,
        LibraryName = "libSceNpManager",
        PreferLle = true)]
    // Ghidra entry 00018ba0; body addresses 668.
    [SysAbiExport(
        Nid = "O80NrhUOPGY",
        ExportName = "sceNpCheckPremium",
        Target = Generation.Gen5,
        LibraryName = "libSceNpManager",
        PreferLle = true)]
    // Ghidra entry 00016bc0; body addresses 273.
    [SysAbiExport(
        Nid = "P6piso307SE",
        ExportName = "sceNpNotifyPremiumFeature",
        Target = Generation.Gen5,
        LibraryName = "libSceNpManager",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpManager LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
