// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpUniversalDataSystem.sprx
// Analyzed provider SHA-256: 0ae12163797cb01f26cca884db98b3a4b137c84143e173021676e854da9ca6bb
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpUniversalDataSystemLleExports
{
    // Ghidra entry 00002400; body addresses 108.
    [SysAbiExport(
        Nid = "JmgwKm96Lq4",
        ExportName = "sceNpUniversalDataSystemEventPropertyArraySetFloat32",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUniversalDataSystem",
        PreferLle = true)]
    // Ghidra entry 000031c0; body addresses 144.
    [SysAbiExport(
        Nid = "YE4dbtbz6OE",
        ExportName = "sceNpUniversalDataSystemEventPropertyObjectSetInt32",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUniversalDataSystem",
        PreferLle = true)]
    // Ghidra entry 00001b70; body addresses 254.
    [SysAbiExport(
        Nid = "jZCqWFgMehE",
        ExportName = "sceNpUniversalDataSystemAbortHandle",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUniversalDataSystem",
        PreferLle = true)]
    // Ghidra entry 000017c0; body addresses 320.
    [SysAbiExport(
        Nid = "wB7IWzGp2v0",
        ExportName = "sceNpUniversalDataSystemDestroyContext",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUniversalDataSystem",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpUniversalDataSystem LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
