// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceNpUtility.sprx
// Analyzed provider SHA-256: 80f7cedc7007c3f8dd0d2ecb6db7a005e1e76216bef7b932d81913585c80e572
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class NpUtilityLleExports
{
    // Ghidra entry 00008910; body addresses 206.
    [SysAbiExport(
        Nid = "BYIZGKm6bO4",
        ExportName = "sceNpBandwidthTestGetStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUtility",
        PreferLle = true)]
    // Ghidra entry 000087f0; body addresses 53.
    [SysAbiExport(
        Nid = "hqzi1IHdQQQ",
        ExportName = "sceNpBandwidthTestInitStartDownload",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUtility",
        PreferLle = true)]
    // Ghidra entry 00008920; body addresses 7.
    [SysAbiExport(
        Nid = "kvdMF48mB3Y",
        ExportName = "sceNpBandwidthTestAbort",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUtility",
        PreferLle = true)]
    // Ghidra entry 000087b0; body addresses 53.
    [SysAbiExport(
        Nid = "mA0zsbqm+kA",
        ExportName = "sceNpBandwidthTestInitStartUpload",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUtility",
        PreferLle = true)]
    // Ghidra entry 000088d0; body addresses 20.
    [SysAbiExport(
        Nid = "pLr1fEQS1z8",
        ExportName = "sceNpBandwidthTestShutdown",
        Target = Generation.Gen5,
        LibraryName = "libSceNpUtility",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] NpUtility LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
