// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libScePlayerInvitationDialog.sprx
// Analyzed provider SHA-256: 1c2924a5c0fa156299cda9e9ba55433690f7372f809464c0fc4ba6e33d3a569b
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class PlayerInvitationDialogLleExports
{
    // Ghidra entry 00000650; body addresses 77.
    [SysAbiExport(
        Nid = "gDm5a6GSE94",
        ExportName = "scePlayerInvitationDialogTerminate",
        Target = Generation.Gen5,
        LibraryName = "libScePlayerInvitationDialog",
        PreferLle = true)]
    // Ghidra entry 00000430; body addresses 120.
    [SysAbiExport(
        Nid = "kFhuwHrIUqs",
        ExportName = "scePlayerInvitationDialogUpdateStatus",
        Target = Generation.Gen5,
        LibraryName = "libScePlayerInvitationDialog",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] PlayerInvitationDialog LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
