// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceRandom.sprx
// Analyzed provider SHA-256: 4af0ac1f1dc40c45a267a13f623e87080bf11cdedc210c1062e474d59b98b8fd
// The semantic fallback for the provider export is implemented by
// SharpEmu.Libs.Random.RandomExports. Keep this helper unregistered so there
// is exactly one Gen5 owner for PI7jIZj4pcE.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class RandomLleExports
{
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Random LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
