// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceRtc.sprx
// Analyzed provider SHA-256: 2af66216f6717b56c484552fb096e0dda4d75b3b559ff58610ce65dff5be121b
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class RtcLleExports
{
    // Ghidra entry 00001160; body addresses 966.
    [SysAbiExport(
        Nid = "99bMGglFW3I",
        ExportName = "sceRtcParseRFC3339",
        Target = Generation.Gen5,
        LibraryName = "libSceRtc",
        PreferLle = true)]
    // Ghidra entry 00001fc0; body addresses 10.
    [SysAbiExport(
        Nid = "WJ3rqFwymew",
        ExportName = "sceRtcFormatRFC3339",
        Target = Generation.Gen5,
        LibraryName = "libSceRtc",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Rtc LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
