// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceShare.native.sprx
// Analyzed provider SHA-256: 02b41c8d10cc86418a7b3182a972d0a24163791eaf67a187ac6d1df531e4560d
// Each registration prefers the loaded guest export. The remaining feature-
// prohibit fallback is deliberately fail-closed and never claims provider
// behavior; feature permit has a semantic HLE contract in ShareExports.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class ShareLleExports
{
    // Ghidra entry 00006d30; body addresses 39.
    [SysAbiExport(
        Nid = "5wjxESwX68I",
        ExportName = "sceShareFeatureProhibit",
        Target = Generation.Gen5,
        LibraryName = "libSceShare",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Share LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
