// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceSharePlay.sprx
// Analyzed provider SHA-256: d41598603a31066e405fb2f60e5d848b36d12b0b109c3862f8d5eba93ae0ddb4
// Each registration prefers the loaded guest export. The two lifecycle
// entries below preserve the provider contract when no guest provider loads;
// any remaining shared fallback stays deliberately fail-closed.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class SharePlayLleExports
{
    private const ulong RequiredWorkspaceSize = 0x1800;
    private const int SharePlayErrorInvalidWorkspace = unchecked((int)0x810E0001);
    private const int SharePlayErrorAlreadyInitialized = unchecked((int)0x810E0003);
    private const int SharePlayErrorNotInitialized = unchecked((int)0x810E0004);
    private static readonly object StateGate = new();
    private static bool _initialized;

    // Ghidra entry 00000a90; body addresses 18.
    [SysAbiExport(
        Nid = "UaLjloJinow",
        ExportName = "sceSharePlayTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceSharePlay",
        PreferLle = true)]
    public static int SharePlayTerminate(CpuContext ctx)
    {
        lock (StateGate)
        {
            if (!_initialized)
            {
                return ctx.SetReturn(SharePlayErrorNotInitialized);
            }

            _initialized = false;
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
    }

    // Ghidra entry 00000a60; body addresses 36.
    [SysAbiExport(
        Nid = "isruqthpYcw",
        ExportName = "sceSharePlayInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceSharePlay",
        PreferLle = true)]
    public static int SharePlayInitialize(CpuContext ctx)
    {
        var workspace = ctx[CpuRegister.Rdi];
        var workspaceSize = ctx[CpuRegister.Rsi];
        lock (StateGate)
        {
            if (_initialized)
            {
                return ctx.SetReturn(SharePlayErrorAlreadyInitialized);
            }

            // The provider allocates an internal 0x1800-byte workspace when
            // the pointer is null. A caller-owned workspace must be at least
            // 0x1800 bytes; it remains opaque and has no ABI output fields.
            if (workspace != 0 && workspaceSize < RequiredWorkspaceSize)
            {
                return ctx.SetReturn(SharePlayErrorInvalidWorkspace);
            }

            _initialized = true;
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
    }

    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] SharePlay LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }

    internal static bool IsInitializedForTests
    {
        get
        {
            lock (StateGate)
            {
                return _initialized;
            }
        }
    }

    internal static void ResetForTests()
    {
        lock (StateGate)
        {
            _initialized = false;
        }
    }
}
