// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceSigninDialog.sprx
// Analyzed provider SHA-256: bc1e3b69a190e27649a540e556bc96382c69bad597784f162af2b788c84b27fb
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class SigninDialogLleExports
{
    // Ghidra entry 00001700; body addresses 12.
    [SysAbiExport(
        Nid = "Bw31liTFT3A",
        ExportName = "sceSigninDialogUpdateStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceSigninDialog",
        PreferLle = true)]
    // Ghidra entry 000016e0; body addresses 15.
    [SysAbiExport(
        Nid = "JlpJVoRWv7U",
        ExportName = "sceSigninDialogOpen",
        Target = Generation.Gen5,
        LibraryName = "libSceSigninDialog",
        PreferLle = true)]
    // Ghidra entry 000016d0; body addresses 12.
    [SysAbiExport(
        Nid = "LXlmS6PvJdU",
        ExportName = "sceSigninDialogTerminate",
        Target = Generation.Gen5,
        LibraryName = "libSceSigninDialog",
        PreferLle = true)]
    // Ghidra entry 000016c0; body addresses 12.
    [SysAbiExport(
        Nid = "mlYGfmqE3fQ",
        ExportName = "sceSigninDialogInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceSigninDialog",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] SigninDialog LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
