// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceSystemService.sprx
// Analyzed provider SHA-256: 6bcb5dd125d9d09b6053f383ba89b1613335bff5ab83870f0bd732b767f4aac9
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class SystemServiceLleExports
{
    // Ghidra entry 00000250; body addresses 1007.
    [SysAbiExport(
        Nid = "656LMQSrg6U",
        ExportName = "sceSystemServiceReceiveEvent",
        Target = Generation.Gen5,
        LibraryName = "libSceSystemService",
        PreferLle = true)]
    // Ghidra entry 00002ec0; body addresses 29.
    [SysAbiExport(
        Nid = "m5CYKX20wfg",
        ExportName = "sceSystemServiceInitializePlayerDialogParam",
        Target = Generation.Gen5,
        LibraryName = "libSceSystemService",
        PreferLle = true)]
    // Ghidra entry 00002ee0; body addresses 293.
    [SysAbiExport(
        Nid = "uaieF+glFPs",
        ExportName = "sceSystemServiceLaunchPlayerDialog",
        Target = Generation.Gen5,
        LibraryName = "libSceSystemService",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] SystemService LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
