// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceVideoRecording.native.sprx
// Analyzed provider SHA-256: 6b2adfdf208c96b37680927cfc9837598f4d01d96536cd49c72d693d84749537
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class VideoRecordingPrivateLleExports
{
    // Ghidra entry 0000b970; body addresses 14.
    [SysAbiExport(
        Nid = "7QoTYzVuzto",
        ExportName = "sceVideoRecordingOpen",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000c090; body addresses 163.
    [SysAbiExport(
        Nid = "KHvkPQJDMLk",
        ExportName = "sceVideoRecordingClose",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000c180; body addresses 50.
    [SysAbiExport(
        Nid = "OOFxrMY+mfI",
        ExportName = "sceVideoRecordingStop",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000b4b0; body addresses 523.
    [SysAbiExport(
        Nid = "ZvWzS2wTIMc",
        ExportName = "sceVideoRecordingQueryMemSize",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000b480; body addresses 47.
    [SysAbiExport(
        Nid = "fZJQzFK4Gv4",
        ExportName = "sceVideoRecordingGetStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000b8a0; body addresses 201.
    [SysAbiExport(
        Nid = "iQS6DUtLybE",
        ExportName = "iQS6DUtLybE#L#A",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000b320; body addresses 59.
    [SysAbiExport(
        Nid = "sA6+5XdbqMA",
        ExportName = "sceVideoRecordingGetInfo",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    // Ghidra entry 0000c140; body addresses 50.
    [SysAbiExport(
        Nid = "tWoe9IlGAhs",
        ExportName = "sceVideoRecordingStart",
        Target = Generation.Gen5,
        LibraryName = "libSceVideoRecordingP",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] VideoRecordingP LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
