// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2_PUBLIC_20260605 program: libSceVoice.sprx
// Analyzed provider SHA-256: bacd6c18bde775e27eade58f33460c86a7cad68b5c2716ce12b6bec8bd138df3
// Each registration prefers the loaded guest export. Most HLE fallbacks remain
// fail-closed; sceVoiceInit has a Ghidra-backed lifecycle fallback below.

using System.Buffers.Binary;
using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class VoiceLleExports
{
    private const int VoiceErrorNotInitialized = unchecked((int)0x804E0801);
    private const int VoiceErrorAlreadyInitialized = unchecked((int)0x804E0802);
    private const int VoiceErrorInvalidArgument = unchecked((int)0x804E0805);
    private const int VoiceInitParameterSize = 0x28;
    private const int VoiceThreadParameterSize = 0x30;

    private static readonly object StateGate = new();
    private static readonly byte[] InitParameters = new byte[VoiceInitParameterSize];
    private static readonly byte[] ThreadParameters = new byte[VoiceThreadParameterSize];
    private static int _initialized;
    private static int _threadParametersConfigured;
    private static uint _version;

    // Ghidra entry 00017bf0; body addresses 165.
    [SysAbiExport(
        Nid = "54phPH2LZls",
        ExportName = "sceVoiceStart",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017ca0; body addresses 132.
    [SysAbiExport(
        Nid = "Ao2YNSA7-Qo",
        ExportName = "sceVoiceStop",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019970; body addresses 83.
    [SysAbiExport(
        Nid = "CrLqDwWLoXM",
        ExportName = "sceVoiceGetPortInfo",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00017b40; body addresses 161.
    [SysAbiExport(
        Nid = "Oo0S5PH7FIQ",
        ExportName = "sceVoiceEnd",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018650; body addresses 196.
    [SysAbiExport(
        Nid = "QBFoAIjJoXQ",
        ExportName = "sceVoiceSetVolume",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 000198e0; body addresses 71.
    [SysAbiExport(
        Nid = "YeJl6yDlhW0",
        ExportName = "sceVoiceWriteToIPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019790; body addresses 168.
    [SysAbiExport(
        Nid = "ajVj3QG2um4",
        ExportName = "sceVoiceDisconnectIPortFromOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019840; body addresses 149.
    [SysAbiExport(
        Nid = "b7kJI+nx2hg",
        ExportName = "sceVoiceDeletePort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018890; body addresses 184.
    [SysAbiExport(
        Nid = "cJLufzou6bc",
        ExportName = "sceVoiceGetBitRate",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019930; body addresses 64.
    [SysAbiExport(
        Nid = "cQ6DGsQEjV4",
        ExportName = "sceVoiceReadFromOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00018a10; body addresses 338.
    [SysAbiExport(
        Nid = "elcxZTEfHZM",
        ExportName = "sceVoiceGetPortAttr",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 00019560; body addresses 185.
    [SysAbiExport(
        Nid = "nXpje5yNpaE",
        ExportName = "sceVoiceCreatePort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    // Ghidra entry 000196e0; body addresses 168.
    [SysAbiExport(
        Nid = "oV9GAdJ23Gw",
        ExportName = "sceVoiceConnectIPortToOPort",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] Voice LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }

    // Ghidra entry 00017a90; body addresses 167. The provider rejects a null
    // parameter, snapshots five qwords, records the second argument in its
    // initialization descriptor, and rejects a second live initialization.
    [SysAbiExport(
        Nid = "9TrhuGzberQ",
        ExportName = "sceVoiceInit",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    public static int InitializeWithoutGuestProvider(CpuContext ctx)
    {
        lock (StateGate)
        {
            if (_initialized != 0)
            {
                return ctx.SetReturn(VoiceErrorAlreadyInitialized);
            }

            var parameterAddress = ctx[CpuRegister.Rdi];
            if (parameterAddress == 0)
            {
                return ctx.SetReturn(VoiceErrorInvalidArgument);
            }

            Span<byte> parameters = stackalloc byte[VoiceInitParameterSize];
            if (!ctx.Memory.TryRead(parameterAddress, parameters))
            {
                return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);
            }

            parameters.CopyTo(InitParameters);
            _version = unchecked((uint)ctx[CpuRegister.Rsi]);
            _initialized = 1;
            return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
        }
    }

    // Ghidra provider entry 00017e60 dispatches operation 0x20 to 00014170,
    // which rejects an uninitialized service before applying the 0x30-byte
    // selector-1 structure in 0000d500. Selector zero is an accepted no-op.
    [SysAbiExport(
        Nid = "clyKUyi3RYU",
        ExportName = "sceVoiceSetThreadsParams",
        Target = Generation.Gen5,
        LibraryName = "libSceVoice",
        PreferLle = true)]
    public static int SetThreadsParamsWithoutGuestProvider(CpuContext ctx)
    {
        lock (StateGate)
        {
            if (_initialized == 0)
            {
                return ctx.SetReturn(VoiceErrorNotInitialized);
            }

            var parameterAddress = ctx[CpuRegister.Rdi];
            if (parameterAddress == 0)
            {
                return ctx.SetReturn(VoiceErrorInvalidArgument);
            }

            Span<byte> selectorBytes = stackalloc byte[sizeof(uint)];
            if (!ctx.Memory.TryRead(parameterAddress, selectorBytes))
            {
                return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);
            }

            var selector = BinaryPrimitives.ReadUInt32LittleEndian(selectorBytes);
            if (selector == 0)
            {
                return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
            }

            if (selector != 1)
            {
                return ctx.SetReturn(VoiceErrorInvalidArgument);
            }

            Span<byte> parameters = stackalloc byte[VoiceThreadParameterSize];
            if (!ctx.Memory.TryRead(parameterAddress, parameters))
            {
                return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_MEMORY_FAULT);
            }

            parameters.CopyTo(ThreadParameters);
            _threadParametersConfigured = 1;
            return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_OK);
        }
    }

    internal static void ResetForTests()
    {
        lock (StateGate)
        {
            Array.Clear(InitParameters);
            Array.Clear(ThreadParameters);
            _version = 0;
            _threadParametersConfigured = 0;
            _initialized = 0;
        }
    }

    internal static uint VersionForTests
    {
        get
        {
            lock (StateGate)
            {
                return _version;
            }
        }
    }

    internal static bool ThreadParametersConfiguredForTests
    {
        get
        {
            lock (StateGate)
            {
                return _threadParametersConfigured != 0;
            }
        }
    }

    internal static byte[] ThreadParametersForTests
    {
        get
        {
            lock (StateGate)
            {
                return ThreadParameters.ToArray();
            }
        }
    }
}
