// <auto-generated by scripts/generate-lle-nid-registrations.py />
// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Ghidra 12.1.2 program: libSceWebBrowserDialog.sprx
// Analyzed provider SHA-256: 1b3db8d07aae8aa973ad33f449defc510047031a5d11b6f7084b5a3ce3f42926
// Each registration prefers the loaded guest export. The shared HLE handler
// is deliberately fail-closed and never claims provider behavior.

using SharpEmu.HLE;

namespace SharpEmu.Libs.Lle;

public static class WebBrowserDialogLleExports
{
    // Ghidra entry 00001cb0; body addresses 113.
    [SysAbiExport(
        Nid = "FraP7debcdg",
        ExportName = "sceWebBrowserDialogOpen",
        Target = Generation.Gen5,
        LibraryName = "libSceWebBrowserDialog",
        PreferLle = true)]
    // Ghidra entry 000029d0; body addresses 179.
    [SysAbiExport(
        Nid = "PSK+Eik919Q",
        ExportName = "sceWebBrowserDialogClose",
        Target = Generation.Gen5,
        LibraryName = "libSceWebBrowserDialog",
        PreferLle = true)]
    // Ghidra entry 00002580; body addresses 147.
    [SysAbiExport(
        Nid = "h1dR-t5ISgg",
        ExportName = "sceWebBrowserDialogUpdateStatus",
        Target = Generation.Gen5,
        LibraryName = "libSceWebBrowserDialog",
        PreferLle = true)]
    // Ghidra entry 00001a00; body addresses 587. When the guest provider is
    // unavailable, its initialization path deterministically reports that the
    // browser service is unavailable and creates no state.
    [SysAbiExport(
        Nid = "jqb7HntFQFc",
        ExportName = "sceWebBrowserDialogInitialize",
        Target = Generation.Gen5,
        LibraryName = "libSceWebBrowserDialog",
        PreferLle = true)]
    public static int InitializeWithoutGuestProvider(CpuContext ctx) =>
        ctx.SetReturn(unchecked((int)0x80B8000E));

    // Ghidra entry 000027a0; body addresses 546.
    [SysAbiExport(
        Nid = "vCaW0fgVQmc",
        ExportName = "sceWebBrowserDialogGetResult",
        Target = Generation.Gen5,
        LibraryName = "libSceWebBrowserDialog",
        PreferLle = true)]
    public static int MissingGuestProvider(CpuContext ctx)
    {
        if (string.Equals(Environment.GetEnvironmentVariable("SHARPEMU_LOG_IMPORTS"), "1", StringComparison.Ordinal))
        {
            Console.Error.WriteLine("[LOADER][ERROR] WebBrowserDialog LLE-preferred export reached its fail-closed HLE fallback");
        }

        return ctx.SetReturn(OrbisGen2Result.ORBIS_GEN2_ERROR_NOT_IMPLEMENTED);
    }
}
